# Generated by Django 3.2.7 on 2023-05-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=127)),
                ('logo', models.ImageField(blank=True, upload_to='company/')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('whatsapp', models.URLField(verbose_name='Whatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='Ссыллка на видео')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('name', models.CharField(max_length=127)),
                ('preview', models.ImageField(max_length=127, upload_to='')),
                ('description', models.TextField(verbose_name='Описание')),
                ('name_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='mainapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=127)),
                ('salary', models.CharField(max_length=127)),
                ('type', models.CharField(max_length=127)),
                ('name_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='mainapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=127)),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('website', models.URLField(verbose_name='Ссылка к сайту')),
                ('registration', models.URLField(verbose_name='Регистрация')),
                ('description', models.TextField(verbose_name='Описание')),
                ('name', models.CharField(max_length=127)),
                ('image', models.ImageField(upload_to='events/')),
                ('name_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mainapp.company')),
            ],
        ),
    ]
